emit:
  - "@typespec/openapi3"
  - "@typespec/protobuf"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/schema"
    openapi-versions:
      - 3.0.0
  "@typespec/protobuf":
    emitter-output-dir: "{output-dir}/protobuf"
    


