name: API Lint

on:           
  push:
    branches: [ "**" ]
    paths:
      - 'openapi3/openapi.yaml'
  pull_request:

jobs:
  spectral-lint-swaggerhub-sync:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣  Get the repo code
      - uses: actions/checkout@v4

      # 2️⃣  Set up Node (needed for the CLI)
      - uses: actions/setup-node@v4
        with:
          node-version: "20"         # any LTS works
      - name: Install Spectral CLI
        run: npm i -g @stoplight/spectral@latest
      - name: Spectral Lint
        run: |
          npx spectral lint "openapi3/openapi.yaml" \
            --ruleset .spectral.yaml \
            --format stylish \
            --fail-severity warn
      - name: Sync OpenAPI to SwaggerHub
        env:
          SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
        run: |
          API_VERSION=$(grep -m 1 "version" openapi3/openapi.yaml | cut -d':' -f2 | tr -d ' ')
          curl -X POST "https://api.swaggerhub.com/apis/demoorg-9f2/notes-api/$API_VERSION?isPrivate=true&version=$API_VERSION&oas=3.0.3&force=true" \
            -H "Content-Type: application/yaml" \
            -H "Authorization: $SWAGGERHUB_API_KEY" \
            --data-binary @openapi3/openapi.yaml      
  