name: API Lint

on:           
  push:
    branches: [ "**" ]
    paths:
      - 'openapi3/openapi.yaml'
  pull_request:

jobs:
  spectral-lint-swaggerhub-sync:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣  Get the repo code
      - uses: actions/checkout@v4

      # 2️⃣  Set up Node (needed for the CLI)
      - uses: actions/setup-node@v4
        with:
          node-version: "20"         # any LTS works
      - name: Install Spectral CLI
        run: npm i -g @stoplight/spectral@latest
      - name: Spectral Lint
        run: |
          npx spectral lint "openapi3/openapi.yaml" \
            --ruleset .spectral.yaml \
            --format stylish \
            --fail-severity warn
      - name: Sync to SwaggerHub
        uses: swaggerhub/actions/sync@v1
        with:
          api: 'demoorg-9f2/notes-api'
          version: 1.0.0
          file: 'openapi3/openapi.yaml'
          token: ${{ secrets.SWAGGERHUB_API_KEY }}    
  